import Head from "next/head";
import Header from "./Header";
import { ReactNode } from "react";


export default function Layout({ children }: { children: ReactNode }) {
    return (
        <>
          <Head>
            <title>Create next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          <main className="main-content">{children}</main>
        </>
    );
};